server:
  shutdown: graceful

spring:
  application:
    name: shop-api
  profiles:
    active: dev
  lifecycle:
    timeout-per-shutdown-phase: 30s

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true # ??? ?? ???? ??????. ?? JPA ???? ?????? ??? ?? ?? ?????? ?, ?????? ??? ???? ??? ?????.

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true


    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka

  instance:
    prefer-ip-address: true

management:
  health:
    status:
      order: DOWN, UP
  endpoint:
    jolokia:
      enabled: true
    metrics:
      enabled: true
    pause:
      enabled: true
    resume:
      enabled: true
    restart:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

# 환경 변수로 넣어주기
nhncloud:
  storage:
    url: https://kr1-api-object-storage.nhncloudservice.com/v1/AUTH_c20e3b10d61749a2a52346ed0261d79e
    token: gAAAAABncmfGvi_pGv8CsEIFkLKJMDuzeSZqycOVD2hKr4U7c_UvHUXYMWolr0lB_pdZ2Fkg7gq2f9zhH71vbH-UcsoACaiRx0JdbdTxVdGOjN-xDi6uUjpCDxNwhQDKDhaerkWNHT5IniJWkLaR_xe7yrD7srfR_AsoGcbIOljf1iYsyIhdZQw
    container: aurora # 컨테이너 이름


### key manager
key:
  manager:
    url: https://api-keymanager.nhncloudservice.com
    path: /keymanager/v1.0/appkey/{app-key}/secrets/{key-id}
    app-key: qTQNj7LyHhdAazH3
    password: 5555

aladin:
  api:
    base-url: https://www.aladin.co.kr/ttb/api
    ttb-key: ttbrkdtkscjs10916001