server:
  port: 9280

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB      # 파일 크기 제한
      max-request-size: 10MB

  data:
    redis:
      host: na
      port: 0      #각자 쓰고있는 포트에 따라 변경
      database: 1
      username:
      password: na

api:
  gateway:
    base-url: localhost:9180