server:
  shutdown: graceful

spring:
  application:
    name: shop-api
  profiles:
    active: dev
  lifecycle:
    timeout-per-shutdown-phase: 30s

#    datasource:
#      url: jdbc:mysql://localhost:3306/taskapi?useSSL=false&serverTimezone=UTC
#      username: root
#      password: P@ssw0rd
#      driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:h2:mem:bookstore;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true # ??? ?? ???? ??????. ?? JPA ???? ?????? ??? ?? ?? ?????? ?, ?????? ??? ???? ??? ?????.

  h2:
    console:
      enabled: true
      path: /h2-console
#logging:
#  level:
#    root: debug
#    org.hibernate.orm.jdbc.bind: trace
#    org.springframework.transaction.interceptor: trace
#
#    sun.rmi: WARN
#    javax.management: WARN


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true


    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka

  instance:
    prefer-ip-address: true

management:
  health:
    status:
      order: DOWN, UP
  endpoint:
    jolokia:
      enabled: true
    metrics:
      enabled: true
    pause:
      enabled: true
    resume:
      enabled: true
    restart:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

nhncloud:
  storage:
    url: fill
    token: fill
