logging:
  level:
    org.springframework.web: WARN

#storage:
#  nhn:
#    bucket-name: your-nhn-bucket
#    endpoint: https://kr.object.nhncloud.com
#    access-key: your-access-key
#    secret-key: your-secret-key

#spring:
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 10MB
#      max-request-size: 10MB