server:
  port: 8083
  shutdown: graceful

spring:
  application:
    name: shop-api
  profiles:
    active: dev
  lifecycle:
    timeout-per-shutdown-phase: 30s
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/taskapi?useSSL=false&serverTimezone=UTC
  #    username: root
  #    password: P@ssw0rd
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true # ??? ?? ???? ??????. ?? JPA ???? ?????? ??? ?? ?? ?????? ?, ?????? ??? ???? ??? ?????.
  datasource:
    url: jdbc:h2:mem:bookstore;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
#logging:
#  level:
#    root: debug
#    org.hibernate.orm.jdbc.bind: trace
#    org.springframework.transaction.interceptor: trace
#
#    sun.rmi: WARN
#    javax.management: WARN


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true


    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka

  instance:
    prefer-ip-address: true

management:
  health:
    status:
      order: DOWN, UP
  endpoint:
    jolokia:
      enabled: true
    metrics:
      enabled: true
    pause:
      enabled: true
    resume:
      enabled: true
    restart:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

## key manager
key:
  manager:
    url: https://api-keymanager.nhncloudservice.com
    path: /keymanager/v1.0/appkey/{app-key}/secrets/{keyId}
    app-key: qTQNj7LyHhdAazH3
    password: 123

## mysql
database:
  mysql:
    url: 0a26e1278d3d47ddaabe34348c5ad3d8
    user-name: d05aa6d9bd8e44a6b2e775b429935482
    password: a2eaad61880140b7a53cd7f48856f26c
    initial-size: 10
    max-total: 10
    min-idle: 10
    max-idle: 10
    max-wait: 1000
